### ISSUE TITLE
Unable to create a secondary index using a String [JIRA: CLIENTS-188]

### ISSUE THREAD

**Issue by sbishep** [basho/riak-ruby-client#211]
I'm working straight from the docs at http://docs.basho.com/riak/latest/dev/using/2i/

From IRB I cannot set any indexes to strings. Using sets works, but that is not the desired functionality I'm looking for.  Here is an example:

```
2.2.0 :014 > client = Riak::Client.new                                                                                                                            
 => #<Riak::Client [#<Node 127.0.0.1:8087>]> 
2.2.0 :015 > bucket = client.bucket_type('default').bucket('users')                                                                                               
 => #<Riak::BucketTyped::Bucket {default/users}> 
2.2.0 :016 > obj.content_type = 'application/json'                                                                                                                
 => "application/json" 
2.2.0 :017 > obj.raw_data = '{"user_data":{}}'                                                                                                                    
 => "{\"user_data\":{}}" 
2.2.0 :018 > obj.indexes['twitter_bin'] = 'jsmith123'                                                                                                             
 => "jsmith123" 
2.2.0 :019 > obj.save
NoMethodError: undefined method `save' for #<Riak::RObject:0x000000021e7218>
        from (irb):19
        from /home/deployer/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :020 > obj.store
NoMethodError: undefined method `map' for "jsmith123":String
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake/object_methods.rb:90:in `encode_index'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake/object_methods.rb:19:in `block in dump_object'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake/object_methods.rb:19:in `each'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake/object_methods.rb:19:in `map'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake/object_methods.rb:19:in `dump_object'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client/beefcake_protobuffs_backend.rb:135:in `store_object'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client.rb:396:in `block in store_object'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client.rb:341:in `block in recover_from'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/innertube-1.0.2/lib/innertube.rb:127:in `take'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client.rb:339:in `recover_from'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client.rb:311:in `protobuffs'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/client.rb:395:in `store_object'
        from /home/deployer/.rvm/gems/ruby-2.2.0/gems/riak-client-2.2.0.pre1/lib/riak/robject.rb:138:in `store'
        from (irb):20
        from /home/deployer/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```

I'm not quite sure what I'm doing wrong here, but I looked at the encode_index method and it would not work with a String.

**Comment by bkerley** [comment]
Secondary index tagging allows you to tag an object with multiple index values, which is why it wants a `Set`, `Array`, or other `map`-able collection: http://basho.github.io/riak-ruby-client/2i.html#toc-tagging

Summoning @lucperkins because it's a docs bug today, but I'll consider what the "right" thing to do is when 2i-tagging an object with a scalar instead of a collection.

**Comment by sbishep** [comment]
Thanks @bkerley for the quick response.  The use case from the docs is exactly what I need to use in my code.  I want to be able to tag the object with a string.  The code listed in the HTTP interface works  properly. It just seems to be an issue with the ruby client.

**Comment by bkerley** [comment]
Use an array with just the string: `[your_string]`

**Comment by sbishep** [comment]
I've done that as a workaround in my code. It is very confusing that all the docs show being able to set the index to a string or int when both fail.

**Comment by bkerley** [comment]
Agreed.

**Comment by bkerley** [comment]
Documentation has been patched in https://github.com/basho/basho_docs/pull/1536 , should be published soon.

**Comment by sbishep** [comment]
Thanks!

**Comment by bkerley** [comment]
Docs updated: http://docs.basho.com/riak/latest/dev/using/2i/

**Comment by Basho-JIRA** [comment]
Closing as the related GitHub issue was Closed. 

***[posted via JIRA by Derek Somogyi]***
