### ISSUE TITLE
Some tests fail running under OSX

### ISSUE THREAD

**Issue by alexmoore** [basho/riak-ruby-client#276]
New tests pass, but getting errors on these tests in OS X:

```
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

riak-ruby-client(features/lrb/optional-timestamp-conversion-gh-274) $ rspec spec/integration/riak/protobuffs/timeouts_spec.rb
Run options:
  include {:focus=>true}
  exclude {:yes_security=>true}

All examples were filtered out; ignoring {:focus=>true}

Protocol Buffers
  timeouts
    raises error on write timeout (FAILED - 1)
    raises error on connect timeout
    raises error on read timeout (FAILED - 2)

Failures:

  1) Protocol Buffers timeouts raises error on write timeout
     Failure/Error: Thread.start(server.accept) do |s|
     Errno::EBADF:
       Bad file descriptor
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:105:in `accept'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:105:in `block (5 levels) in <top (required)>'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:103:in `loop'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:103:in `block (4 levels) in <top (required)>'

  2) Protocol Buffers timeouts raises error on read timeout
     Failure/Error: Thread.start(server.accept) do |s|
     Errno::EBADF:
       Bad file descriptor
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:35:in `accept'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:35:in `block (5 levels) in <top (required)>'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:33:in `loop'
     # ./spec/integration/riak/protobuffs/timeouts_spec.rb:33:in `block (4 levels) in <top (required)>'

Finished in 0.87003 seconds (files took 0.50747 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/integration/riak/protobuffs/timeouts_spec.rb:92 # Protocol Buffers timeouts raises error on write timeout
rspec ./spec/integration/riak/protobuffs/timeouts_spec.rb:23 # Protocol Buffers timeouts raises error on read timeout

Randomized with seed 8069
```

**Comment by lukebakken** [comment]
@alexmoore or @christophermancini I nominate one of you to reproduce and fix this. I have no access to OS X and I :heart: it that way :smile:
