### ISSUE TITLE
Errors when using beefcake 1.2.0 [JIRA: CLIENTS-949]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak-ruby-client#282]
This PR protobuf-ruby/beefcake#70 introduced changes that affect the integration test suite, causing these failures:

```
Failures:

  1) Encoding and CRDTs with utf-8 strings updates registers in maps
     Failure/Error: expect(map.registers[random_string]).to eq random_string

       expected: "🚴こんにちはสวัสดีibreqol3lt"
            got: nil

       (compared using ==)
     Shared Example Group: "CRDTs with weird names" called from ./spec/integration/riak/encodings/crdt_spec.rb:67
     # ./spec/integration/riak/encodings/crdt_spec.rb:41:in `block (3 levels) in <top (required)>'

  2) Encoding and CRDTs with utf-8 strings updates sets
     Failure/Error: expect(set.members).to include random_string

       expected #<Set: {"\xF0\x9F\x9A\xB4\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF\xE0\xB8\xAA\xE0\xB8\xA7\xE0\xB8\xB1\xE0\xB8\xAA\xE0\xB8\x94\xE0\xB8\xB52yi6ccih4m"}> to include "🚴こんにちはสวัสดี2yi6ccih4m"
       Diff:
       @@ -1,2 +1,2 @@
       -["🚴こんにちはสวัสดี2yi6ccih4m"]
       +["\xF0\x9F\x9A\xB4\xE3\x81\x93\xE3\x82\x93\xE3\x81\xAB\xE3\x81\xA1\xE3\x81\xAF\xE0\xB8\xAA\xE0\xB8\xA7\xE0\xB8\xB1\xE0\xB8\xAA\xE0\xB8\x94\xE0\xB8\xB52yi6ccih4m"]
     Shared Example Group: "CRDTs with weird names" called from ./spec/integration/riak/encodings/crdt_spec.rb:67
     # ./spec/integration/riak/encodings/crdt_spec.rb:55:in `block (3 levels) in <top (required)>'

Finished in 3 minutes 53.4 seconds (files took 0.68485 seconds to load)
830 examples, 2 failures

Failed examples:

rspec ./spec/integration/riak/encodings/crdt_spec.rb[1:1:2] # Encoding and CRDTs with utf-8 strings updates registers in maps
rspec ./spec/integration/riak/encodings/crdt_spec.rb[1:1:3] # Encoding and CRDTs with utf-8 strings updates sets
```

The addition of `dup` means that the original string was no longer forced into `binary` encoding, and we must have depended on that behavior. I have to dig in further.

**Comment by Basho-JIRA** [comment]
Fixed, or closed via GitHub issues. 

***[posted via JIRA by Alexander Moore]***
